'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contact
    Public Property ContactId As Integer
    Public Property Fullname As String
    Public Property Gender As Byte
    Public Property Tel1 As String
    Public Property Tel2 As String
    Public Property Tel3 As String
    Public Property Tel4 As String
    Public Property Company As String
    Public Property Unit As String
    Public Property Description As String

End Class
