'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property UserId As Long
    Public Property Username As String
    Public Property Password As String
    Public Property LastLoginDate As Date
    Public Property CreateDate As Date
    Public Property Email As String

End Class
